### ISSUE TITLE
can't generate image???

### ISSUE THREAD

**Issue by stefiiijugo** [juzeon/SydneyQt#156]
so uh when i try to generate an image it says "cannot find image creation result"?

**Comment by juzeon** [comment]
Can you provide your prompt?

**Comment by stefiiijugo** [comment]
well i tried some prompts that i guess activated their filters, so i tried asking to generate a picture of a dog, and it still said the same thing?

**Comment by juzeon** [comment]
Is you logged in and exported the cookies? And try generating an image on Bing's website before trying again.

**Comment by stefiiijugo** [comment]
yeah i have the cookies and have used bing's image gen

**Comment by NostalgiaGit** [comment]
~~Same problem here, and finally I found the solution.~~

~~If you call this function in your default chat session, it will fail to do so. But if you create a new chat session, the image generation function will work normally and you'll see the images in your chat context.~~

Sorry, I failed when I tried once more. It seems that the problem is not here, I need to study it further.

**Comment by stefiiijugo** [comment]
damn

**Comment by NostalgiaGit** [comment]
Well, it got fixed for me with a new cookie file.

I have no idea why it worked initially but then failed in my previous experiment. I just went to www.bing.com, asked Bing AI to generate an image in the sidebar, and then exported the cookie using the cookie-editor extension. 

After replacing the cookies.json with the new one and restarting the app, everything works fine. :joy:

**Comment by stefiiijugo** [comment]
ok ill try that

**Comment by stefiiijugo** [comment]
yeah it works thanks dude
