### ISSUE TITLE
[BUG] Base64 Does Not Work

### ISSUE THREAD

**Issue by ThePatriotsXOF** [juzeon/SydneyQt#203]
### Checks

- [✓ ] I confirm that I have searched existing issues and couldn't find a similar bug.
- [✓ ] I have read the documentation carefully and it couldn't resolved my problem.

### Describe the bug
Sydney cannot decode base64, it will first write a random python code on a code snippet then asks you to give the base 64 below however if you give the base64 string it will say "Sorry! That's on me, I can't give a response to that right now. What else can I help you with?"

### Expected behavior
Unsure

### Screenshots
![SydneyQt-windows-amd64_18pS2N6iQG](https://github.com/juzeon/SydneyQt/assets/150899804/fb75e1bd-2390-45a6-afc6-e70cad6c7278)
![SydneyQt-windows-amd64_cQo7d4cx6u](https://github.com/juzeon/SydneyQt/assets/150899804/e8b16b35-d71a-47bc-89bf-2bb8dbc9a154)
![SydneyQt-windows-amd64_IvXOOChcBL](https://github.com/juzeon/SydneyQt/assets/150899804/c95765c9-e853-4880-8fff-beaf0db06a9c)

 - OS and Version: Windows 11
 - SydneyQt Version: [e.g. v2.2.7]

### Additional context
Full raw convo
https://pastebin.com/ZJWp4VT9

**Comment by NostalgiaGit** [comment]
If you just remind Bing that the code above is the one you want it to decode, it will work. I don't think it's the app's problem. It's the model itself. The Bing AI model just wasn't smart enough to get you.

**Comment by Cis-Evo** [comment]
I suppose it's not caused by the application. According to your input, it's most likely that the AI has difficulty understanding the garbled characters directly, and it's hard to calculate probability distributions for the output.

My suggestion is to modify the function that decodes a base64 string directly with your base 64 code,and ask it again.
Such as: Please decode base64 for me:" aHR0cHM6Ly9mb3J1bS5tb2JpbGlzbS5vcmcvc2VhcmNoLnBocD9rZXl3b3Jkcz1zd2FwK25vK3Jvb3QmdGVybXM9YWxsJmF1dGhvcj0mc2M9MSZzZj10aXRsZW9u"

**Comment by PeronGH** [comment]
I think this is caused by Microsoft censorship. When the official Bing get censored, it gives the exactly same message as you encountered.
